### ISSUE TITLE
Build is failing on last pull request merge

### ISSUE THREAD

**Issue by viperx77** [Philips-PHM/qlik-cli#4]
npm : npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!
At line:3 char:1
+ npm install
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN deprec...nder installed!:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
qlik-cli@1.1.0 C:\projects\qlik-cli
+-- chalk@2.4.1

**Comment by viperx77** [comment]
@RobWunderlich Please take a look at this.

**Comment by RobWunderlich** [comment]
It looks like this issue is waiting for someone to publish the updated editorconfig. https://github.com/editorconfig/editorconfig-core-js/issues/65
Can we ignore this in the build for now?

**Comment by viperx77** [comment]
Thanks for looking at this but it turned out it was not the warning but the npm auth token had expired.
